server:
  port: ${application.port:8080}
  ssl:
    key-alias: spring-study
    key-store: classpath:keystore.jks
    key-store-password: wlalstjq1

spring:
  pidfile: ./logs/application.pid
  jpa:
    hibernate.ddl-auto: update
    show-sql: false
    database: mysql
  jersey:
    type: filter

context:
  listener:
    classes: org.springframework.boot.system.ApplicationPidFileWriter
