server:
  port: ${application.port:8080}
#  ssl:
#    key-alias: spring-study
#    key-store: classpath:keystore.jks
#    key-store-password: wlalstjq1

spring:
  pidfile: ./logs/application.pid
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    database: mysql
    properties:
      hibernate:
        globally_quoted_identifiers: true
  jersey:
    application-path: /
    type: filter
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# CacheConfig.java로 대체
#  cache:
#    type: redis
#  redis:
#    host: jiminsub.iptime.org
#    port: 6379
#    password: wlalstjq1


context:
  listener:
    classes: org.springframework.boot.system.ApplicationPidFileWriter

management:
  security:
    enabled: false
