server:
  port: ${application.port:8080}

spring:
  jpa:
    hibernate.ddl-auto: update
    show-sql: false
    database: mysql
    properties:
      hibernate:
        globally_quoted_identifiers: true
  jersey:
    type: filter
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

