server:
  port: ${application.port:8080}

spring:
  pidfile: ./logs/application.pid
  jpa:
    hibernate.ddl-auto: update
    show-sql: false
    database: mysql
  jersey:
    type: filter
  cache:
    type: redis
  redis:
    host: jiminsub.iptime.org
    port: 6379
    password: wlalstjq1

context:
  listener:
    classes: org.springframework.boot.system.ApplicationPidFileWriter
